baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Theo's Portfolio
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Home 
          url: /
          weight: 1
        - name: Research
          url: research/
          weight: 2
        # - name: Projects
        #   url: projects/
        #   weight: 3
        - name: Learning Blog
          url: https://cous-cous.netlify.app/
          weight: 4

params:
    description: "This is my portfolio website, containing some of my projects and study notes :D"
    author: Theo Obadiah Teguh
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research", "projects", "learning blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Theo Obadiah Teguh
          subtitle: |
            Hi! I'm Theo, and welcome to my site ( ◠‿◠ ) <br>
            I'm currently an Incoming Machine Learning Researcher at Shanghai Jiaotong University. <br>
            I'll be starting a Master of Statistics at the University of Hong Kong in this year!
            <br><br>

            So far, I worked in several software roles in both industry and academia. I was a Data Scientist
            for Oxbridge Economics under Dr. Yuanshuo Qu. I also worked as a DevOps Engineer, at
            the Vancouver School of Economics under Dr. Jonathan Graves. Finally, I was a Data Engineer at HKU Business School 
            under Dr. Yang Liu and Dr. Yaoyuan Zhang.
            <br><br>

            I just finished a Bachelor of Economics, Finance, and Computer Science at the University of Hong Kong. At
            the same time, I was a Teaching Assistant for COMP1117 and COMP2113.
            <br><br>

            I was born and raised in the city of Jakarta, Indonesia in the land of spicy food 🌴 <br>
            I really enjoy learning cool stuff and teaching it to other people 📖 <br>
                          
          imageUrl: "picture.png"
          imageWidth: 185
          imageHeight: 185
          buttons:
            - name: Resume
              url: cv.pdf
            - name: Research
              url: research/
            # - name: Projects 
            #   url: projects/ # TODO
            - name: Learning Blog
            #   url: learning/ # TODO
              url: https://cous-cous.netlify.app/ # Temporary
            - name: Tags
              url: tags/

    socialIcons:
        - name: Email
          url: mailto:theo.obadiah@gmail.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/theo-obadiah-teguh/
        - name: GitHub
          url: https://github.com/theo-obadiah-teguh

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Theo Obadiah Teguh"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2